### ISSUE TITLE
No chart changes detected

### ISSUE THREAD

**Issue by SapiensAnatis** [helm/chart-testing-action#108]
Hey, I'm probably messing something up here, but every run of the action on my chart repo is saying that nothing has changed when it has. 

Take for instance this run:
https://github.com/SapiensAnatis/helm-charts/actions/runs/4033008969

which was triggered by this commit:
https://github.com/SapiensAnatis/helm-charts/commit/47289587c35a1bad55d4e46ff6b3d1d59563fe2c

It says that nothing has changed when I've clearly updated one of the templates. Additionally, I think my directory structure is sound, with

```
Git repository
├───.github
│   └───workflows
└───charts
    └───dragalia-api
        ├───charts
        └───templates
            └───tests
```

Feel free to look at [the repo itself](https://github.com/SapiensAnatis/helm-charts) but summarily the chart depends on two bitnami charts (redis and postgresql) and has the following `ct.yaml`

```yaml
remote: origin
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
```

When I run the same command that the action is running, `ct list-changed --target-branch master --config ct.yaml --remote=origin` after making a change, I see the chart in the list of changes so not sure what's going on
