### ISSUE TITLE
v2.5.0 is giving an error of `targetBranch main does not exist`

### ISSUE THREAD

**Issue by jessebot** [helm/chart-testing-action#133]
After #132 was fixed (which it was for me), I seem to be seeing the following error with [my job](https://github.com/small-hack/matrix-chart/actions/runs/6705571469/job/18220296597):

```bash
Run changed=$(ct list-changed --target-branch main)
  changed=$(ct list-changed --target-branch main)
  if [[ -n "$changed" ]]; then
    echo "changed=true" >> "$GITHUB_OUTPUT"
  fi
  shell: /usr/bin/bash -e {0}
  env:
    CT_CONFIG_DIR: /opt/hostedtoolcache/ct/3.9.0/amd64/etc
    VIRTUAL_ENV: /opt/hostedtoolcache/ct/3.9.0/amd64/venv
Error: targetBranch 'main' does not exist
Error: Process completed with exit code 1.
```

<details>
  <summary>Here is my full workflow file</summary>
  
  ```yaml
  name: Lint and Test Chart

on:
  pull_request:
    paths:
      - 'charts/matrix/**'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install Helm
        uses: azure/setup-helm@v3.5

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add coturn https://jessebot.github.io/coturn-chart

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.5.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

  ```
  
</details>

In my own repos, I have moved forward, so this probably won't affect me personally for another week or two, but if I understand correctly, this is also affecting others.

Previous comments pertaining to this issue just for record:
https://github.com/helm/chart-testing-action/issues/132#issuecomment-1786998688
https://github.com/helm/chart-testing-action/issues/132#issuecomment-1787140055

**Comment by Eusebiotrigo** [comment]
Happening the same over here.

Seems to be related to https://github.com/helm/chart-testing/issues/577 and https://github.com/helm/chart-testing/pull/601

**Comment by cpanato** [comment]
@jessebot i will try to figure out what is going on today, but be kind i do that in my free time

**Comment by tboerger** [comment]
You are doing a great job @cpanato, thanks for your effort! ;)

**Comment by eyenx** [comment]
Thanks for your effort @cpanato !

**Comment by jessebot** [comment]
> @jessebot i will try to figure out what is going on today, but be kind i do that in my free time

Thanks, friend! Please let me know if my language was not kind and I will amend it :blue_heart:

**Comment by stevehipwell** [comment]
I suspect that this issue might be caused by https://github.com/helm/chart-testing/pull/511; I'm just running a test to revert the `ct` binary back to `v3.8.0` to see if that fixes the issue.

**Comment by stevehipwell** [comment]
I can confirm that setting `version: v3.8.0` in the `with` block fixes the error by reverting the `ct` version.

**Comment by patrick-stephens** [comment]
thanks @stevehipwell for being everywhere I need you :) 
I can confirm this is working for us now as well:
```
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.5.0
        with:
          version: v3.8.0
```
