### ISSUE TITLE
config flag for custom ct.yaml seems to be ignored

### ISSUE THREAD

**Issue by monotek** [helm/chart-testing-action#14]
I've used the config flag for custom ct.yaml but it seems to be ignored as the configured helm extra values for the timeout is not shown in the printed out config.

My step looked like:

```
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@master
        with:
          command: install
          config: /home/runner/work/zammad-helm/zammad-helm/.ci/ct.yaml
```

Action log: https://github.com/zammad/zammad-helm/runs/366239251
