### ISSUE TITLE
directory is not a valid chart directory

### ISSUE THREAD

**Issue by bhanotjyoti** [helm/chart-testing-action#146]
My chart directory structure is 

<img width="279" alt="image" src="https://github.com/helm/chart-testing-action/assets/160529267/7e9c7af4-e91c-4c95-9e03-0339629e0be5">

II have made updates to my template

But I still get this 

```
Linting charts...
Directory "charts-v2/core/base-chart" is not a valid chart directory. Skipping...
Directory "charts-v2/core/base-chart/templates" is not a valid chart directory. Skipping...
Directory "charts-v2/core/base-chart/templates" is not a valid chart directory. Skipping...
Directory "charts-v2/core/base-chart" is not a valid chart directory. Skipping...

------------------------------------------------------------------------------------------------------------------------
No chart changes detected.
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully 
```

I am using this ct.yaml 
```

# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: master
chart-dirs:
  - charts-v2
helm-extra-args: --timeout 600s

```

```
this is the GitHub action 

name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "changed=true" >> "$GITHUB_OUTPUT"
      #     fi

      # - name: Run chart-testing (lint)
      #   if: steps.list-changed.outputs.changed == 'true'
      #   run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      # - name: Create kind cluster
      #   if: steps.list-changed.outputs.changed == 'true'
      #   uses: helm/kind-action@v1.10.0

      # - name: Run chart-testing (install)
      #   if: steps.list-changed.outputs.changed == 'true'
      #   run: ct install --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "{changed}={true}" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

      - name: Create kind cluster
        uses:  helm/kind-action@v1.10.0
        if: ${{ needs.list-changed.outputs.changed }} == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml







```
