### ISSUE TITLE
No .kube directory found

### ISSUE THREAD

**Issue by hbagdi** [helm/chart-testing-action#18]
The ct action was running file but recently we have started seeing the following errors:

```
lstat /home/runner/.kube: no such file or directory
```

Here is the full log: https://github.com/Kong/charts/runs/426141790

**Comment by hbagdi** [comment]
My bad. Apologies for the noise.

**Comment by brew** [comment]
What was the problem? I have this happening too :D would love to know how you fixed it.

**Comment by hbagdi** [comment]
I wish I had posted what I did wrong but I didn't and I have no memory of what was going on here.
:(

**Comment by brew** [comment]
Found the problem in my case: I was trying to pass command line args for `ct lint` in the action's command line i.e.

```yaml
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint --all
```

This didn't work, and instead I populated a ct.yaml config file, which worked.
