### ISSUE TITLE
Helm v3 support

### ISSUE THREAD

**Issue by hairmare** [helm/chart-testing-action#19]
I can configure the action to use the 3.0.0-beta.1 chart-testing image which contains Helm v3.0.1 by setting `jobs.lint-test[].with.image=quay.io/helmpack/chart-testing:v3.0.0-beta.1` as follows.
```yaml
# ...
jobs:
  lint-test:
    steps:
      # ...
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          image: quay.io/helmpack/chart-testing:v3.0.0-beta.1
```
The cr.sh still tries to run `helm init --client-only` leading to `Error: unknown flag: --client-only`.

It looks like cr.sh needs to be updated to support Helm v3. My guess is that the script would need some refactoring in the `helm_init` as well as with the `install_tiller` function being called.

At a glance it looks like the refactoring should either switch to just supporting Helm v3 or it should try to figure out what version of Helm is available and adapt what is needed for the installed version.

Are there any plans to change this? I'd be happy to lend a hand if someone can clarify in which direction you'd like the refactor to go.

This is probably a partial duplicate of https://github.com/helm/chart-testing/issues/188 (looking at https://github.com/helm/chart-testing/issues/188#issuecomment-580887150).
