### ISSUE TITLE
Where should i set the path to the chart

### ISSUE THREAD

**Issue by JohnWillker** [helm/chart-testing-action#21]
HI!

I'm having a problem with the CI not correctly identifying the Chart directory

## What I tried:
My workflow file:
```yaml
name: Helm

on:
  pull_request:
    paths:
      - 'Charts/generic/**'
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
```
### What I hope will happen:
Run the lint only in `Charts/generic` directory.

How to configure this?

**Comment by unguiculus** [comment]
`chart-testing` searches charts in directory `charts` by default. You can reconfigure this with a config file:

*ct.yaml*
```yaml
chart-dirs:
  - my-chart-dir
```

```yaml
- name: Run chart-testing (lint)
  id: lint
  uses: helm/chart-testing-action@v1.0.0-alpha.3
  with:
    command: lint
    config: ct.yaml
```

See:
* https://github.com/helm/chart-testing-action#inputs
* https://github.com/helm/chart-testing#configuration
