### ISSUE TITLE
apiVersion issue in lint

### ISSUE THREAD

**Issue by saikatharryc** [helm/chart-testing-action#30]
I'm having this configuration:
```yaml
name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: lint
          config: ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        with:
          installLocalPathProvisioner: true
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-alpha.3
        with:
          command: install
```

and I'm using apiVersion as `v2` in my chart.
and while using this workflow, it gives me an error and says apiVersion `v2` is not valid.
here is the error: https://github.com/saikatharryc/helm/runs/597069311
and while I do `helm lint` by changing it to `v2`, it says this:

```
➜  helm_chart git:(ci_setup) helm lint ./charts/judge0 
==> Linting ./charts/judge0
[ERROR] Chart.yaml: dependencies are not valid in the Chart file with apiVersion 'v1'. They are valid in apiVersion 'v2'

Error: 1 chart(s) linted, 1 chart(s) failed
```
