### ISSUE TITLE
Extra flags via environment variables

### ISSUE THREAD

**Issue by rgreinho** [helm/chart-testing-action#35]
Can you provide an example with extras arguments via environment variables?

I have been trying to pass the `--validate-maintainers=false`, but all my attempts were unsuccessful.  The documentation mentions that it is possible to use [environment variables](https://github.com/helm/chart-testing#configuration) but they seem ignored by the action.

Here is my step:

```yaml
- name: Run chart-testing (lint)
   id: lint
   env:
     CT_VALIDATE_MAINTAINERS: false 
   uses: helm/chart-testing-action@master
   with:
     command: lint
```
