### ISSUE TITLE
No .kube directory found

### ISSUE THREAD

**Issue by bkimbrough88** [helm/chart-testing-action#36]
I've run into an issue where I get the error "No .kube directory found". Thanks to the discussion on #18, I know that the issue is that I am passing options directly to the `command` like the following:

```
- name: Run chart-testing (install)
  uses: helm/chart-testing-action@v1.0.0-rc.2    
  command: install --helm-repo-extra-args "bw-helm=--username ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD }}"
  config: ct.yaml
```

Note that I do actually use the `ct.yaml` file to pass most of my configuration, however I didn't want to commit secrets to source so I attempted to put them in the `command`. Is there some way we can pass arguments to the command that are either variable or sensative in nature?

**Comment by bkimbrough88** [comment]
So I was able to work around this issue by injecting the values into my `ct.yaml` file at run time, but this feels like a complete hack. Here's my workaround:

```

      - name: Inject secrets into config file
        run: |-
          cat << EOF >> ct.yaml
          helm-repo-extra-args:
            - bw-helm=--username ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD }}
          EOF

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: install
          config: ct.yaml
```
