### ISSUE TITLE
Be able to run without the ct.yaml config file

### ISSUE THREAD

**Issue by max-rocket-internet** [helm/chart-testing-action#41]
First of all, this tool is super nice, thanks!

It would be tidier if we could run it without the `ct.yaml`. I tried these, both don't work:

```yaml
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint --chart-dirs stable
```

```yaml
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
        env:
          CT_CHART_DIRS: stable
```

I know env vars is covered in https://github.com/helm/chart-testing-action/issues/35 but perhaps there's another way?
