### ISSUE TITLE
ct.yaml in workdir overrides "config:"

### ISSUE THREAD

**Issue by smlx** [helm/chart-testing-action#53]
I have a `ct.yaml` in the root of my repo and want to override this for a particular step. I tried this:

```
    - name: Run chart-testing (lint)
      id: lint
      uses: helm/chart-testing-action@v1.0.0
      with:
        command: lint
        config: test-suite.ct.yaml
```

This means:
* `test-suite.ct.yaml` file is mounted to `/etc/ct/ct.yaml` inside the container
* `/workdir` inside the container contains the `ct.yaml` from the root of my repo

Due to the precedence rules of `chart-testing` config files the `/workdir/ct.yaml` is used instead of `/etc/ct/ct.yaml`. This was surprising to me.

It seems like reasonable behaviour once I understood what's going on, but it's something of a gotcha. Would you accept a PR documenting this behaviour in the README?
