### ISSUE TITLE
list-changed command fails without error

### ISSUE THREAD

**Issue by sundowndev** [helm/chart-testing-action#69]
I try to set up a basic helm chart repo but I'm stuck with this issue : 

![image](https://user-images.githubusercontent.com/16480203/121497714-0479a080-c9dc-11eb-9588-934c592688c2.png)

I also tried running `ct list-changed` directly but it does not show anything.

my workflow: 

```yaml
name: Lint and Test Charts

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'charts/**/README.md'
      - 'LICENSE'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed) # <- stuck here
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        id: lint
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0
        with:
          install_local_path_provisioner: true
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        id: install
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config ct.yaml
```

ct.yaml

```yaml
helm-extra-args: --timeout 600s
chart-dirs:
  - charts
target-branch: main
```

file structure : 

```
$ tree
.
├── charts
│   └── driftctl
│       ├── Chart.yaml
│       ├── templates
│       │   ├── _helpers.tpl
│       │   ├── job.yaml
│       │   ├── NOTES.txt
│       │   └── volume-cm.yaml
│       └── values.yaml
├── ct.yaml
├── LICENSE
└── README.md

3 directories, 9 files
```
