### ISSUE TITLE
ct.yaml placed in root of the repository is not being picked

### ISSUE THREAD

**Issue by prashant-shahi** [helm/chart-testing-action#79]
Versions:
```
Run helm/chart-testing-action@v2.2.0
  with:
    version: v3.5.0
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.12/x64/lib
```

I had placed `ct.yaml` in the root of the project but it was not being picked up by `ct`.
However, when I pass those same from the environment variables or pass config file in CLI using `--config ct.yaml`, it works.
