### ISSUE TITLE
Add Mayor version tags to be pinned by actions

### ISSUE THREAD

**Issue by gsanchezgavier** [helm/chart-testing-action#90]
A quite common pattern on actions is to have a mayor version tag like `v2` that will be pointing to the latest release of that mayor. This makes possible to configure the GH workflows pointing to that latest.

```yaml
jobs:
  chart-lint:
    name: Helm chart Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: helm/chart-testing-action@v2
```
